openapi: "3.1.0"
info:
  title: Rapporteringsperiode API
  description: API for å registrere aktiviteter og rapporteringperioder for dagpengemottakere
  version: "1.0.0"
  contact:
      name: '#team-dagpenger'
servers:
    - url: https://dp-rapportering.intern.dev.nav.no
      description: dev
    - url: https://dp-rapportering.intern.nav.no
      description: prod
paths:
  /isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Alive"
  /isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Ready"
  /rapporteringsperioder:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Rapporteringsperiode"
  /rapporteringsperioder/gjeldende:
    get:
      description: ""
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Rapporteringsperiode"
components:
  schemas:
    AktivitetType:
      type: string
      enum:
        - Arbeid
        - Syk
        - Ferie
    Aktivitet:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
            $ref: '#/components/schemas/AktivitetType'
        timer:
          type: "string"
        dato:
          type: "string"
          format: "date"
      required:
      - "id"
      - "type"
      - "timer"
      - "dato"
    RapporteringsperiodeDag:
      type: "object"
      properties:
        dagIndex:
          type: "integer"
          format: "int32"
        dato:
          type: "string"
          format: "date"
        muligeAktiviteter:
          type: "array"
          items:
            $ref: '#/components/schemas/AktivitetType'
        aktiviteter:
          type: "array"
          items:
            $ref: "#/components/schemas/Aktivitet"
      required:
      - "dato"
      - "muligeAktiviteter"
      - "aktiviteter"
    Rapporteringsperiode:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        beregnesEtter:
          type: "string"
          format: "date"
        fraOgMed:
          type: "string"
          format: "date"
        tilOgMed:
          type: "string"
          format: "date"
        status:
          type: "string"
          enum:
          - "TilUtfylling"
          - "Godkjent"
          - "Innsendt"
        dager:
          type: "array"
          items:
            $ref: "#/components/schemas/RapporteringsperiodeDag"
      required:
      - "id"
      - "beregnesEtter"
      - "fraOgMed"
      - "tilOgMed"
      - "status"
      - "dager"
