---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dp-rapportering-alerts
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  groups:
    - name: applikasjon-alerts
      rules:
        - alert: JobFeilet
          expr: sum(rate(dp_rapportering_job_errors_total{namespace="teamdagpenger"}[10m])) by (navn, app) > 0
          for: 0s
          annotations:
            consequence: 'Jobb *\{{ $labels.navn }}* i *\{{ $labels.app }}* fikk feil ved kjøring'
            action: '`kubectl describe pod -l app=\{{ $labels.app}}` -> `kubectl logs -l app=\{{ $labels.app}}`'
          labels:
            namespace: teamdagpenger
            severity: critical