---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: dp-rapportering-alerts
    namespace: teamdagpenger
    labels:
        team: teamdagpenger
spec:
    groups:
        - name: dp-rapportering-minne
          rules:
              - alert: Minneforbruk
                expr: |
                    sum (container_memory_working_set_bytes{container=~"dp-rapportering"}) 
                    < (
                    sum(kube_pod_container_resource_limits{resource="memory", container=~"dp-rapportering"}) / 
                    count(kube_pod_container_resource_limits{resource="memory", container=~"dp-rapportering"}) 
                    * 0.90
                    )
                for: 5m
                annotations:
                    description: 'Minneforbruket til applikasjonen dp-rapportering nærmer seg limit'
                    consequence: 'Applikasjonen kan bli terminert'
                    action: 'Sjekk Grafana for detaljer'
                labels:
                    namespace: teamdagpenger
                    severity: warning
              - alert: CPU-forbruk
                expr: |
                    sum(irate(container_cpu_usage_seconds_total{container=~"dp-rapportering"}[1m])) /
                    sum(machine_cpu_cores) * 100
                    >
                    60
                for: 5m
                annotations:
                    description: 'CPU-forbruk til applikasjonen dp-rapportering er for høy'
                    consequence: 'Applikasjonen kan bli terminert'
                    action: 'Sjekk Grafana for detaljer'
                labels:
                    namespace: teamdagpenger
                    severity: warning
              - alert: Gjennomsnittlig responstid
                expr: |
                    sum(rate(http_request_duration_seconds_sum{container=~"dp-rapportering"}[5m])) /
                    sum(rate(http_request_duration_seconds_count{container=~"dp-rapportering"}[5m]))
                    >
                    1
                for: 5m
                annotations:
                    description: 'Gjennomsnittlig responstid til applikasjonen dp-rapportering er for høy'
                    consequence: 'Brukere kan få ConnectTimeoutException'
                    action: 'Sjekk Grafana for detaljer'
                labels:
                    namespace: teamdagpenger
                    severity: warning
              - alert: Antall feil
                expr: |
                    sum(rate(nginx_ingress_controller_requests{status!~"^[23].*", container=~"dp-rapportering"}[5m]))
                    >
                    10
                for: 5m
                annotations:
                    description: 'Antall feil i applikasjonen dp-rapportering er for høyt'
                    consequence: 'Det er mulig at brukere ikke kan sende meldekort'
                    action: 'Sjekk Grafana for detaljer'
                labels:
                    namespace: teamdagpenger
                    severity: warning
