apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: dp-rapportering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: {{ image }}
  port: 8080

  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}

  tokenx:
    enabled: true

  kafka:
    pool: {{ kafka.pool }}

  leaderElection: true

  envFrom:
    - secret: dp-rapportering-unleash-api-token

  env:
    - name: BEREGNINGSDATO_STRATEGI
      value: {{beregningsdato.strategi}}
    - name: GRUPPER_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: flyway.cleanDisabled
      value: "false"
    - name: MELDEPLIKT_ADAPTER_HOST
      value: {{MELDEPLIKT_ADAPTER_HOST}}
    - name: MELDEPLIKT_ADAPTER_AUDIENCE
      value: {{MELDEPLIKT_ADAPTER_AUDIENCE}}
    - name: PERSONREGISTER_HOST
      value: {{PERSONREGISTER_HOST}}
    - name: PERSONREGISTER_AUDIENCE
      value: {{PERSONREGISTER_AUDIENCE}}
    - name: PDF_GENERATOR_URL
      value: {{PDF_GENERATOR_URL}}
    - name: GITHUB_SHA
      value: {{ githubSha }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_URL
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_URL }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE }}
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_URL
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_URL }}
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE }}
    - name: BEKREFTELSE_TOPIC
      value: {{ BEKREFTELSE_TOPIC }}
    - name: JDK_JAVA_OPTIONS # Bytter GC og lar JVMen se at det er flere CPU kjerner
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
  gcp:
      sqlInstances:
          - type: POSTGRES_15
            highAvailability: true
            diskAutoresize: true
            pointInTimeRecovery: false
            autoBackupHour: 3
            tier: {{gcp.sql.tier}}
            databases:
                - name: rapportering
                  envVarPrefix: DB
            flags:
                - name: cloudsql.enable_pgaudit
                  value: "true"
                - name: pgaudit.log
                  value: 'write'
  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  accessPolicy:
    outbound:
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
      rules:
        - application: dp-arena-meldeplikt-adapter
        - application: dp-behov-pdf-generator
        - application: dp-rapportering-personregister
        - application: paw-kafka-key-generator
          namespace: paw
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        - application: dp-rapportering-frontend
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp

  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
