apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: dp-rapportering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: {{ image }}
  port: 8080

  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}

  tokenx:
    enabled: true

  env:
    - name: BEREGNINGSDATO_STRATEGI
      value: {{beregningsdato.strategi}}
    - name: GRUPPER_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: flyway.cleanDisabled
      value: "false"
    - name: MELDEPLIKT_ADAPTER_HOST
      value: {{MELDEPLIKT_ADAPTER_HOST}}

  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  accessPolicy:
    outbound:
      rules:
        - application: dp-arena-meldeplikt-adapter
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        - application: dp-rapportering-frontend
        {{#if wonderwalled}}
        - application: tokenx-token-generator
          namespace: aura
        - application: wonderwalled-azure
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        {{/if}}

  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
