apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isalive
  readiness:
    path: /isready
  startup:
    path: /isready
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  tokenx:
    enabled: true
  env:
    - name: BEREGNINGSDATO_STRATEGI
      value: {{beregningsdato.strategi}}
    - name: GRUPPER_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: flyway.cleanDisabled
      value: "false"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: rapportering
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        - application: dp-rapportering-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-idporten
          namespace: aura
        - application: wonderwalled-azure
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        {{/if}}
