apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    domene: behandling
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  liveness:
    path: /isalive
  readiness:
    path: /isready
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: rapportering
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        - application: dp-rapportering-frontend
        {{#if wonderwalled}}
        - application: wonderwalled-idporten
          namespace: aura
        {{/if}}
