# Sett token og periodeId i http-client filene. Velg miljø før kjøring.
###
POST {{url}}/rapporteringsperiode/{{periodeId}}/arbeidssoker
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "registrertArbeidssoker": true
}
