openapi: 3.0.0
info:
  title: Rapporteringsperiode API
  version: 1.0.0
  description: API for å registrere aktiviteter og rapporteringsperioder
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dagpenger.intern.dev.nav.no/v1
    description: dev
  - url: https://dagpenger.intern.nav.no/v1
    description: prod
paths:
  /aktivitet:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aktivitet'
          description: OK
      summary: Hent all aktivitet
      description: Henter ut alle registrerte aktiviteter
      operationId: get-aktiviteter
      tags:
        - Aktivitet
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AktivitetInput'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aktivitet'
          description: Created
      summary: Lagrer en aktivitet
      description: Legger en ny aktivitet til i tidslinjen
      operationId: post-aktiviteter
      tags:
        - Aktivitet
  /aktivitet/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aktivitet'
          description: OK
        '404':
          description: Not Found
      summary: Hent en bestemt aktivitet etter ID
      description: ''
      operationId: get-aktivitet-id
      tags:
        - Aktivitet
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AktivitetInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aktivitet'
          description: OK
      summary: Gjør endringer på en eksisterende aktivitet
      description: Kan vel bare endre timetall
      operationId: put-aktivitet-id
      tags:
        - Aktivitet
    delete:
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      summary: Slett en aktivitet
      description: ''
      operationId: delete-aktivitet-id
      tags:
        - Aktivitet
    parameters:
      - name: id
        description: ID til aktiviteten som skal oppdateres eller slettes
        schema:
          type: integer
        in: path
        required: true
  /rapporteringsperioder:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
      summary: Hent alle rapporteringsperioder
      description: Lister ut alle rapporteringsperioder, både aktive og historiske
      operationId: get-rapporteringsperiode
      tags:
        - Rapporteringsperiode
  /rapporteringsperioder/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
        '404':
          description: Not Found
      summary: Hent en bestemt rapporteringsperiode
      description: Henter ut en rapporteringsperiod
      operationId: get-rapporteringsperiode-id
      tags:
        - Rapporteringsperiode
    parameters:
      - name: id
        description: ID til rapporteringsperioden
        schema:
          type: string
          format: uuid
        in: path
        required: true
  /rapporteringsperioder/{id}/innsending:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
      summary: Send inn en rapporteringsperiode
      description: Send inn en rapporteringsperiode
      operationId: post-rapporteringsperiode-ferdigstill
      tags:
        - Rapporteringsperiode
    parameters:
      - name: id
        description: ID of the reporting period to get or correct
        schema:
          type: integer
        in: path
        required: true
components:
  schemas:
    AktivitetType:
      type: string
      enum:
        - Arbeid
        - Syk
        - Ferie
    Aktivitet:
      required:
        - type
        - dato
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/AktivitetType'
        timer:
          type: number
        dato:
          format: date
          type: string
      example:
        id: 4a49e571-6384-4eab-9c2e-3f4d48d30b9a
        type: Arbeid
        timer: 8
        dato: '2023-05-05'
    AktivitetInput:
      required:
        - type
        - dato
      type: object
      properties:
        type:
          $ref: '#/components/schemas/AktivitetType'
        timer:
          type: number
        dato:
          format: date
          type: string
    Rapporteringsperiode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fraOgMed:
          format: date
          type: string
        tilOgMed:
          format: date
          type: string
        status:
          type: string
          example: TilUtfylling
        dager:
          type: array
          items:
            type: object
            properties:
              dagIndex:
                type: number
              dato:
                type: string
                format: date
              muligeAktiviteter:
                type: array
                items:
                  $ref: '#/components/schemas/AktivitetType'
        aktiviteter:
          type: array
          items:
            $ref: '#/components/schemas/Aktivitet'
    PeriodeKorreksjonsInput:
      required:
        - fraOgMed
        - tilOgMed
      type: object
      properties:
        fraOgMed:
          format: date
          type: string
        tilOgMed:
          format: date
          type: string
      example:
        fraOgMed: '2023-05-01'
        tilOgMed: '2023-05-15'
  securitySchemes:
    tokenx:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [TokenX](https://docs.nais.io/security/auth/tokenx/) til autentisering. Du må utveksle IDporten-token
        til et TokenX-token hvor `audience` er satt til `[cluster]:teamdagpenger:dp-rapportering`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-rapportering)
  headers: { }
  responses: { }
  parameters: { }
tags:
  - name: Aktivitet
    description: >-
      Lager en tidslinje med all aktivitet bruker har utført i en periode med
      rapporteringsplikt
  - name: Rapporteringsperiode
    description: >-
      Rapporteringsperioder representerer hvilke perioder man må eller har meldt
      seg for
security:
  - tokenx: [ ]