openapi: 3.0.0
info:
  title: Rapporteringsperiode API
  version: 1.0.0
  description: API for å registrere aktiviteter og rapporteringsperioder
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dp-rapportering.intern.dev.nav.no
    description: dev
  - url: https://dp-rapportering.intern.nav.no
    description: prod
paths:
  /rapporteringsperioder:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
      summary: Hent alle rapporteringsperioder
      description: Lister ut alle rapporteringsperioder, både aktive og historiske
      operationId: get-rapporteringsperiode
      tags:
        - Rapporteringsperiode
      security:
        - tokenX: [ ]
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
        '404':
          description: Not Found
      requestBody:
        required: true
        content:
          application/json:
            examples:
              Uten fraOgMed:
                description: Er det bare ident som settes vil fraOgMed bruke dagens dato som standardverdi
                value:
                  ident: "12312312311"
              Med fraOgMed:
                description: Skal rapporteringsperioden gjelde fra en bestemt dato settes fraOgMed
                value:
                  ident: "12312312311"
                  fraOgMed: "2023-03-09"
            schema:
              $ref: '#/components/schemas/Rapporteringsperiode.Ny'
      summary: Opprett en rapporteringsperiode
      description: Opprett ut en rapporteringsperiode.
      operationId: post-rapporteringsperiode
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
  /rapporteringsperioder/sok:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
      summary: Søk etter rapporteringsperioder
      description: |
        Lister ut alle rapporteringsperioder som treffer søket. Har en periode blitt korrigert så er det den siste korrigeringen som blir vist. 
      
        Ønsker man perioden som har blitt korrigert må man hente ut denne via `/rapporteringsperioder/{periodeId}`.
      operationId: post-rapporteringsperiode-sok
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rapporteringsperiode.Sok'
  /rapporteringsperioder/gjeldende:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
        '404':
          description: Not Found
      summary: Henter ut gjeldende rapporteringsperiode
      description: Henter ut en rapporteringsperiode. Henter alltid den siste perioden som gjelder for tidsrommet og må fylles ut. Henter ikke ut påstartede korrigeringer.
      operationId: get-rapporteringsperiode-gjeldende
      tags:
        - Rapporteringsperiode
      security:
        - tokenX: [ ]
  /rapporteringsperioder/{periodeId}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
        '404':
          description: Not Found
      summary: Hent en bestemt rapporteringsperiode
      description: Henter ut en rapporteringsperiod
      operationId: get-rapporteringsperiode-id
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
        - tokenX: [ ]
    parameters:
      - $ref: '#/components/parameters/periodeId'
  /rapporteringsperioder/{periodeId}/godkjenn:
    post:
      responses:
        '200':
          description: OK
      summary: Godkjenner en rapporteringsperiode
      description: Godkjenner en rapporteringsperiode
      operationId: put-rapporteringsperiode-godkjenn
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
        - tokenX: [ ]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Godkjenn.Ny'
    parameters:
      - name: periodeId
        description: ID til rapporteringsperioden
        schema:
          type: integer
        in: path
        required: true
  /rapporteringsperioder/{periodeId}/avgodkjenn:
    post:
      responses:
        '200':
          description: OK
      summary: Avgodkjenner en rapporteringsperiode
      description: Avgodkjenner en rapporteringsperiode
      operationId: put-rapporteringsperiode-avgodkjenn
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
        - tokenX: [ ]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Godkjenn.Ny'
    parameters:
      - name: periodeId
        description: ID til rapporteringsperioden
        schema:
          type: integer
        in: path
        required: true
  /rapporteringsperioder/{periodeId}/korrigering:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rapporteringsperiode'
          description: OK
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                title: Bare innsendte rapporteringsperioder kan korrigeres
                status: 405
          description: Ulovlig tilstand
      summary: Lag en korrigering for en rapporteringsperiode
      description: Lager en korrigering for en rapporteringsperiode
      operationId: post-rapporteringsperiode-korrigering
      tags:
        - Rapporteringsperiode
      security:
        - azureAd: [ ]
        - tokenX: [ ]
      parameters:
      - $ref: '#/components/parameters/periodeId'
  /rapporteringsperioder/{periodeId}/aktivitet:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aktivitet.Ny'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aktivitet'
          description: Created
      summary: Lagrer en aktivitet
      description: Legger en ny aktivitet til i tidslinjen
      operationId: post-aktiviteter
      tags:
        - Aktivitet
      security:
        - azureAd: [ ]
        - tokenX: [ ]
      parameters:
        - $ref: '#/components/parameters/periodeId'
  /rapporteringsperioder/{periodeId}/aktivitet/{aktivitetId}:
    delete:
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      summary: Slett en aktivitet
      description: ''
      operationId: delete-aktivitet-id
      tags:
        - Aktivitet
      security:
        - azureAd: [ ]
        - tokenX: [ ]
    parameters:
      - $ref: '#/components/parameters/periodeId'
      - name: aktivitetId
        description: ID til aktiviteten som skal oppdateres eller slettes
        schema:
          type: string
          format: uuid
        in: path
        required: true
components:
  schemas:
    AktivitetType:
      type: string
      enum:
        - Arbeid
        - Syk
        - Ferie
    Aktivitet:
      required:
        - type
        - dato
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/AktivitetType'
        timer:
          type: string
          format: ISO8601 Duration
          description: Må representeres som en ISO8601 Duration
        dato:
          format: date
          type: string
      example:
        id: 4a49e571-6384-4eab-9c2e-3f4d48d30b9a
        type: Arbeid
        timer: PT8H30M
        dato: '2023-05-05'
    Aktivitet.Ny:
      required:
        - type
        - dato
      type: object
      properties:
        type:
          $ref: '#/components/schemas/AktivitetType'
        timer:
          type: string
          format: ISO8601 Duration
        dato:
          format: date
          type: string
    Rapporteringsperiode.Sok:
      type: object
      required:
        - ident
      properties:
        ident:
          type: string
    Rapporteringsperiode.Ny:
      type: object
      required:
        - ident
      properties:
        ident:
          type: string
        fraOgMed:
          type: string
          format: date
          description: Standardverdi er dagens dato
    Godkjenn.Ny:
      type: object
      required:
        - begrunnelse
      properties:
        begrunnelse:
          type: string
    Rapporteringsperiode:
      required:
        - periodeId
        - fraOgMed
        - tilOgMed
        - status
        - dager
      type: object
      properties:
        id:
          type: string
          format: uuid
        fraOgMed:
          format: date
          type: string
        tilOgMed:
          format: date
          type: string
        korrigerer:
          type: string
          format: uuid
          nullable: true
        korrigertAv:
          type: string
          format: uuid
          nullable: true
        status:
          type: string
          enum:
            - TilUtfylling
            - Godkjent
            - Innsendt
          example: TilUtfylling
        dager:
          type: array
          items:
            type: object
            required:
              - dagIndex
              - dato
              - muligeAktiviteter
              - aktiviteter
            properties:
              dagIndex:
                type: integer
              dato:
                type: string
                format: date
              muligeAktiviteter:
                type: array
                items:
                  $ref: '#/components/schemas/AktivitetType'
              aktiviteter:
                type: array
                items:
                  $ref: '#/components/schemas/Aktivitet'
    PeriodeKorreksjonsInput:
      required:
        - fraOgMed
        - tilOgMed
      type: object
      properties:
        fraOgMed:
          format: date
          type: string
        tilOgMed:
          format: date
          type: string
      example:
        fraOgMed: '2023-05-01'
        tilOgMed: '2023-05-15'
    Problem:
      type: object
      description: Implementasjon av Problem Details for HTTP APIs [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
      properties:
        type:
          type: string
          format: uri
          default: about:blank
          description: URI som identifiserer problemet
        title:
          type: string
          description: En kort oppsummering av problemet
        status:
          type: integer
          description: HTTP status
        detail:
          type: string
          description: Forklaring av problemet
        instance:
          type: string
          format: uri
          description: Hvor feilen oppstod
  securitySchemes:
    azureAd:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [AzureAD](https://docs.nais.io/security/auth/azure-ad) til autentisering. 
        Token må ha `audience` satt til `[cluster]:teamdagpenger:dp-rapportering`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-rapportering)
    tokenX:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [TokenX](https://docs.nais.io/security/auth/tokenx/) til autentisering. Du må utveksle IDporten-token
        til et TokenX-token hvor `audience` er satt til `[cluster]:teamdagpenger:dp-rapportering`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-rapportering)
  headers: { }
  responses: { }
  parameters:
    periodeId:
      name: periodeId
      description: ID til rapporteringsperioden
      schema:
        type: string
        format: uuid
      in: path
      required: true

tags:
  - name: Rapporteringsperiode
    description: >-
      Rapporteringsperioder representerer hvilke perioder man må eller har meldt
      seg for
  - name: Aktivitet
    description: >-
      Lager en tidslinje med all aktivitet bruker har utført i en periode med
      rapporteringsplikt