openapi: 3.0.0
info:
    title: Rapporteringsperiode API
    version: 1.0.0
    description: API for å fylle og endre rapporteringsperioder
    contact:
        name: '#team-dagpenger-rapportering'
servers:
    - url: https://dp-rapportering.intern.dev.nav.no
      description: dev
    - url: https://dp-rapportering.intern.nav.no
      description: prod
paths:
    /harmeldeplikt:
        get:
            responses:
                '200':
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: true
                    description: OK
            summary: Sjekker om bruker har DP-meldeplikt
            description: Returnerer "true" hvis bruker har DP-meldeplikt, ellers returnerer "false"
            operationId: get-har-meldeplikt
            tags:
                - HarMeldeplikt
            security:
                -   tokenX: [ ]

    /rapporteringsperioder:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Rapporteringsperiode'
                    description: OK
                '204':
                    description: No Content
            summary: Hent alle rapporteringsperioder som ikke er sendt inn
            description: Lister ut alle rapporteringsperioder som ikke er sendt inn
            operationId: get-rapporteringsperioder
            tags:
                - Rapporteringsperioder
            security:
                - tokenX: [ ]

    /rapporteringsperioder/innsendte:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Rapporteringsperiode'
                    description: OK
                '204':
                    description: No Content
            summary: Hent alle tidligere innsendte rapporteringsperioder
            description: Lister ut alle rapporteringsperioder som har blitt sendt inn
            operationId: get-innsendte-rapporteringsperioder
            tags:
                - Rapporteringsperioder
            security:
                - tokenX: []

    /rapporteringsperiode:
        post:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Rapporteringsperiode'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InnsendingResponse'
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InnsendingResponse'
                404:
                    description: Not Found
            summary: Innsending av rapporteringsperiode
            description: Sender inn en utfylt rapporteringsperiode
            operationId: post-rapporteringsperiode-id
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []

    /rapporteringsperiode/{periodeId}:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Rapporteringsperiode'
                    description: OK
                '404':
                    description: Not Found
            summary: Hent en bestemt rapporteringsperiode
            description: Henter ut en rapporteringsperiod
            operationId: get-rapporteringsperiode-id
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: [ ]
        parameters:
            - $ref: '#/components/parameters/periodeId'
            - name: Hent-Original
              in: header
              required: false
              schema:
                type: boolean
                default: true
              description: Bestemmer om perioden skal oppdateres med data fra baksystem eller kun hentes direkte fra databasen


    /rapporteringsperiode/{periodeId}/start:
        post:
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            summary: Start utfylling av rapporteringsperiode
            description: Lagrer rapporteringsperioden i databasen så den er klar til utfylling
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/arbeidssoker:
        post:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ArbeidssokerRequest'
            responses:
                204:
                    description: No Content - OK
                400:
                    description: Bad Request
            summary: Oppdater registrert arbeidssøker
            description: Oppdatering av om om bruker vil fortsette å stå registrert som arbeidssøker i neste periode
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/aktivitet:
        post:
            responses:
                204:
                    description: OK - No Content
                400:
                    description: Bad Request
            summary: Lagre aktiviteter
            description: Oppretter/oppdaterer aktiviteter på en dag i rapporteringsperioden
            operationId: post-lagre-aktivitet
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/dag'
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/aktiviteter:
        delete:
            responses:
                204:
                    description: OK - No Content
                400:
                    description: Bad Request
            summary: Slette alle aktiviteter
            description: Slette alle aktiviteter i rapporteringsperioden
            operationId: post-slett-aktivitet
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/begrunnelse:
        post:
            responses:
                204:
                    description: OK - No Content
                400:
                    description: Bad Request
            summary: Lagre begrunnelse for endring
            description: Oppdaterer begrunnelse for endring i rapporteringsperioden
            operationId: post-oppdater-begrunnelse
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BegrunnelseRequest'
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/rapporteringstype:
        post:
            responses:
                204:
                    description: OK - No Content
                400:
                    description: Bad Request
            summary: Lagre rapporteringstype for perioden
            description: Oppdaterer rapporteringstype i rapporteringsperioden
            operationId: post-oppdater-rapporteringstype
            tags:
                - Rapporteringsperiode
            security:
                - tokenX: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RapporteringstypeRequest'
        parameters:
            - $ref: '#/components/parameters/periodeId'

    /rapporteringsperiode/{periodeId}/endre:
        post:
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Rapporteringsperiode'
                400:
                    description: Bad request - kunne ikke endre rapporteringsperiode
                500:
                    description: Internal server error - Finner ikke original rapporteringsperiode
            summary: Opprett endring av rapporteringsperiode
            description: Oppretter endring av rapporteringsperiode. Returnerer rapporteringsperiode med ny id og status Endret
            operationId: post-rapporteringsperiode-id-endre
            tags:
                - Rapporteringsperiode
            security:
                -   tokenX: [ ]
        parameters:
            -   $ref: '#/components/parameters/periodeId'


components:
    schemas:
        ArbeidssokerRequest:
            required:
                - registrertArbeidssoker
            type: object
            properties:
                registrertArbeidssoker:
                    type: boolean
        AktivitetType:
            type: string
            enum:
                - Arbeid
                - Syk
                - Utdanning
                - Fravaer
        Aktivitet:
            required:
                - id
                - type
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                type:
                    $ref: '#/components/schemas/AktivitetType'
                timer:
                    type: string
                    format: ISO8601 Duration
                    description: Må representeres som en ISO8601 Duration
            example:
                id: 4a49e571-6384-4eab-9c2e-3f4d48d30b9a
                type: Arbeid
                timer: PT8H30M
        BegrunnelseRequest:
            required:
                - begrunnelseEndring
            type: object
            properties:
                begrunnelseEndring:
                    type: string
        InnsendingFeil:
            type: object
            required:
                - kode
            properties:
                kode:
                    type: string
                params:
                    type: array
                    items:
                        type: string
        InnsendingResponse:
            type: object
            required:
                - id
                - status
            properties:
                id:
                    type: number
                status:
                    type: string
                    enum:
                        - OK
                        - FEIL
                feil:
                    type: array
                    items:
                        $ref: '#/components/schemas/InnsendingFeil'
        RapporteringstypeRequest:
            required:
                - rapporteringstype
            type: object
            properties:
                rapporteringstype:
                    type: string
        periode:
            type: object
            required:
                - fraOgMed
                - tilOgMed
            properties:
                fraOgMed:
                    type: string
                    format: date
                tilOgMed:
                    type: string
                    format: date
        dag:
            type: array
            items:
                type: object
                required:
                    - dato
                    - aktiviteter
                    - dagIndex
                properties:
                    dato:
                        type: string
                        format: date
                    aktiviteter:
                        type: array
                        items:
                            $ref: '#/components/schemas/Aktivitet'
                    dagIndex:
                        type: number
        periodeId:
            type: object
            properties:
                id:
                    type: string
        Rapporteringsperiode:
            required:
                - id
                - periode
                - dager
                - kanSendesFra
                - kanSendes
                - kanEndres
                - status
            type: object
            properties:
                id:
                    type: string
                periode:
                    $ref: '#/components/schemas/periode'
                dager:
                    $ref: '#/components/schemas/dag'
                kanSendesFra:
                    type: string
                    format: date
                kanSendes:
                    type: boolean
                kanEndres:
                    type: boolean
                bruttoBelop:
                    type: number
                begrunnelseEndring:
                    type: string
                status:
                    $ref: '#/components/schemas/RapporteringsperiodeStatus'
                mottattDato:
                    type: string
                    format: date
                registrertArbeidssoker:
                    type: boolean
                originalId:
                    type: string
                html:
                    type: string
                rapporteringstype:
                    type: string
        RapporteringsperiodeStatus:
            type: string
            enum:
                - TilUtfylling
                - Endret
                - Innsendt
                - Ferdig
                - Feilet
        Problem:
            type: object
            description: Implementasjon av Problem Details for HTTP APIs [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
            properties:
                type:
                    type: string
                    format: uri
                    default: about:blank
                    description: URI som identifiserer problemet
                title:
                    type: string
                    description: En kort oppsummering av problemet
                status:
                    type: integer
                    description: HTTP status
                detail:
                    type: string
                    description: Forklaring av problemet
                instance:
                    type: string
                    format: uri
                    description: Hvor feilen oppstod
    securitySchemes:
        tokenX:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: |
                Bruker [TokenX](https://docs.nais.io/security/auth/tokenx/) til autentisering. Du må utveksle IDporten-token
                til et TokenX-token hvor `audience` er satt til `[cluster]:teamdagpenger:dp-rapportering`.
                
                For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
                - [dev-gcp](https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-rapportering)
    headers: { }
    responses: { }
    parameters:
        periodeId:
            name: periodeId
            description: ID til rapporteringsperioden
            schema:
                type: string
            in: path
            required: true
        aktivitetId:
            name: aktivitetId
            description: ID til aktivitet
            schema:
                type: string
            in: path
            required: true

tags:
    - name: Rapporteringsperiode
      description: >-
          Rapporteringsperioder representerer hvilke perioder man må eller har meldt
          seg for
